### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by maxigs** [jordanbtucker/odrive-crypt#4]
Hi Jordan,

Thanks for building this nice tool, i hope odrive rewards you for it, as it might get them some new customers on pro (me included) if decryption without their client/subscription works. :)

I just installed it via NPM and wanted to try it on the first file but fails with the following error:

```
$ odrive-crypt -i Md4e5Ci1MC93X1AAAaqmTOiNYkdAiWw1rQliYvYvH14AezGMcY7FzxY= -o ~/
Passphrase:
/usr/local/lib/node_modules/odrive-crypt/src/bin.js:171
		callback()
		^

TypeError: callback is not a function
    at FileDecipher.odriveCrypt.decryptFile.err (/usr/local/lib/node_modules/odrive-crypt/src/bin.js:171:3)
    at emitNone (events.js:91:20)
    at FileDecipher.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jordanbtucker** [comment]
Thanks for the bug report. I just published v0.0.6. Can you please see if it's fixed?

**Comment by maxigs** [comment]
Just updated and still get the same error.

I also tried removing the old and re-installing it, just in case. No luck.

I tried digging a bit in the code and found that `decryptDirectoryItems` (https://github.com/jordanbtucker/odrive-crypt/blob/master/src/bin.js#L214) expects a callback, that it does not get when called from `decrypt` (https://github.com/jordanbtucker/odrive-crypt/blob/master/src/bin.js#L129). No idea if this is even relevant.

Decrypting a folder works fine, btw :)

**Comment by jordanbtucker** [comment]
I'm not sure why these callback errors aren't being caught in my tests, but I think they're fixed now in v0.0.7.

In your case, it was [`decryptFile`](https://github.com/jordanbtucker/odrive-crypt/blob/v0.0.6/src/bin.js#L145) that was causing the error, but `decryptDirectoryItems` should have been causing the same error, however you say that decrypting a folder works without error.

Out of curiosity, was the file successfully decrypted even though you were getting an error?
